
import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import SearchBar from "./components/SearchBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-poppins", // Optional if you're using CSS variables
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <div className="flex gap-4">
          <SideBar />
          <div className="space-y-8 hide-scrollbar flex-[85%]">
            <div className="mt-2">
              <SearchBar />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
